name: Publish package to NPM

on:
  workflow_dispatch:

jobs:
  version:
    name: Version Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Publish
        run: npm publish --access public
